In [ ]:
from pathlib import Path
from pprint import pprint

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
PROJECT_ROOT = Path().resolve().parent
REPORT_PATH = PROJECT_ROOT / "report-ml-regression-2026-05-29.joblib"

assert REPORT_PATH.exists()

In [ ]:
REPORT_PATH_2 = PROJECT_ROOT / "report-service-group-kfold.joblib"

assert REPORT_PATH_2.exists()

In [ ]:
data = joblib.load(REPORT_PATH)
len(data)

7

In [ ]:
data["summary"]

                       coverage            mae                rmse            \
                           mean  std      mean       std      mean       std
model
extra_trees                 1.0  0.0  0.003947  0.000041  0.008826  0.000316
random_forest               1.0  0.0  0.004069  0.000041  0.008656  0.000297
hist_gradient_boosting      1.0  0.0  0.013090  0.000251  0.027548  0.000729
location_median             1.0  0.0  0.110851  0.000616  0.160910  0.000605
global_median               1.0  0.0  0.140664  0.000278  0.196408  0.000464

                             mse           median_ae                ...  \
                            mean       std      mean           std  ...
model                                                               ...
extra_trees             0.000078  0.000006  0.002472  8.784105e-06  ...
random_forest           0.000075  0.000005  0.002524  9.894505e-06  ...
hist_gradient_boosting  0.000759  0.000040  0.007920  1.347996e-04  ...
location_median         0.025892  0.000195  0.080000  2.403703e-17  ...
global_median           0.038576  0.000183  0.110000  0.000000e+00  ...

                          ae_q75              ae_q90              ae_q95  \
                            mean       std      mean       std      mean
model
extra_trees             0.005000  0.000022  0.007956  0.000046  0.010718
random_forest           0.005195  0.000022  0.008337  0.000045  0.011313
hist_gradient_boosting  0.014877  0.000186  0.025358  0.000320  0.036800
location_median         0.144000  0.005477  0.220000  0.000000  0.298000
global_median           0.190000  0.000000  0.272000  0.004472  0.360000

                                    ae_q99             ae_q100
                             std      mean       std      mean       std
model
extra_trees             0.000136  0.025056  0.000499  0.621666  0.188579
random_forest           0.000121  0.026104  0.000883  0.512438  0.127276
hist_gradient_boosting  0.000870  0.100711  0.003767  0.855376  0.102556
location_median         0.004472  0.592000  0.004472  1.624000  0.069138
global_median           0.000000  0.720000  0.007071  1.530000  0.007071

[5 rows x 28 columns]

In [ ]:
REPORT_PATH_2 = PROJECT_ROOT / "report-service-group-kfold.joblib"

assert REPORT_PATH_2.exists()

In [ ]:
_data = joblib.load(REPORT_PATH_2)
len(_data)

8

In [ ]:
_data["summary"]

                              coverage                 mae            \
                                  mean       std      mean       std
model
service_location_then_global  0.999996  0.000004  0.017799  0.000093

                                  rmse                 mse            \
                                  mean       std      mean       std
model
service_location_then_global  0.029421  0.000321  0.000866  0.000019

                             median_ae            ...    ae_q75            \
                                  mean       std  ...      mean       std
model                                             ...
service_location_then_global  0.012176  0.000065  ...  0.022184  0.000103

                                ae_q90              ae_q95            \
                                  mean       std      mean       std
model
service_location_then_global  0.036262  0.000142  0.049671  0.000295

                                ae_q99             ae_q100
                                  mean       std      mean       std
model
service_location_then_global  0.108182  0.000881  0.926211  0.198739

[1 rows x 28 columns]

In [ ]:
df = pd.concat([data["summary"], _data["summary"]])

In [ ]:
df

                              coverage                 mae            \
                                  mean       std      mean       std
model
extra_trees                   1.000000  0.000000  0.003947  0.000041
random_forest                 1.000000  0.000000  0.004069  0.000041
hist_gradient_boosting        1.000000  0.000000  0.013090  0.000251
location_median               1.000000  0.000000  0.110851  0.000616
global_median                 1.000000  0.000000  0.140664  0.000278
service_location_then_global  0.999996  0.000004  0.017799  0.000093

                                  rmse                 mse            \
                                  mean       std      mean       std
model
extra_trees                   0.008826  0.000316  0.000078  0.000006
random_forest                 0.008656  0.000297  0.000075  0.000005
hist_gradient_boosting        0.027548  0.000729  0.000759  0.000040
location_median               0.160910  0.000605  0.025892  0.000195
global_median                 0.196408  0.000464  0.038576  0.000183
service_location_then_global  0.029421  0.000321  0.000866  0.000019

                             median_ae                ...    ae_q75            \
                                  mean           std  ...      mean       std
model                                                 ...
extra_trees                   0.002472  8.784105e-06  ...  0.005000  0.000022
random_forest                 0.002524  9.894505e-06  ...  0.005195  0.000022
hist_gradient_boosting        0.007920  1.347996e-04  ...  0.014877  0.000186
location_median               0.080000  2.403703e-17  ...  0.144000  0.005477
global_median                 0.110000  0.000000e+00  ...  0.190000  0.000000
service_location_then_global  0.012176  6.471817e-05  ...  0.022184  0.000103

                                ae_q90              ae_q95            \
                                  mean       std      mean       std
model
extra_trees                   0.007956  0.000046  0.010718  0.000136
random_forest                 0.008337  0.000045  0.011313  0.000121
hist_gradient_boosting        0.025358  0.000320  0.036800  0.000870
location_median               0.220000  0.000000  0.298000  0.004472
global_median                 0.272000  0.004472  0.360000  0.000000
service_location_then_global  0.036262  0.000142  0.049671  0.000295

                                ae_q99             ae_q100
                                  mean       std      mean       std
model
extra_trees                   0.025056  0.000499  0.621666  0.188579
random_forest                 0.026104  0.000883  0.512438  0.127276
hist_gradient_boosting        0.100711  0.003767  0.855376  0.102556
location_median               0.592000  0.004472  1.624000  0.069138
global_median                 0.720000  0.007071  1.530000  0.007071
service_location_then_global  0.108182  0.000881  0.926211  0.198739

[6 rows x 28 columns]

In [ ]:
columns = [pair for pair in df.columns if pair[-1] == "mean"]
df[columns]

,coverage,mae,rmse,mse,median_ae,max_ae,ae_q00,ae_q25,ae_q50,ae_q75,ae_q90,ae_q95,ae_q99,ae_q100
,mean,mean,mean,mean,mean,mean,mean,mean,mean,mean,mean,mean,mean,mean
model,,,,,,,,,,,,,,
extra_trees,1.000000,0.003947,0.008826,0.000078,0.002472,0.621666,0.000000e+00,0.000881,0.002472,0.005000,0.007956,0.010718,0.025056,0.621666
random_forest,1.000000,0.004069,0.008656,0.000075,0.002524,0.512438,5.551115e-18,0.000883,0.002524,0.005195,0.008337,0.011313,0.026104,0.512438
hist_gradient_boosting,1.000000,0.013090,0.027548,0.000759,0.007920,0.855376,7.139322e-08,0.003576,0.007920,0.014877,0.025358,0.036800,0.100711,0.855376
location_median,1.000000,0.110851,0.160910,0.025892,0.080000,1.624000,0.000000e+00,0.040000,0.080000,0.144000,0.220000,0.298000,0.592000,1.624000
global_median,1.000000,0.140664,0.196408,0.038576,0.110000,1.530000,0.000000e+00,0.050000,0.110000,0.190000,0.272000,0.360000,0.720000,1.530000
service_location_then_global,0.999996,0.017799,0.029421,0.000866,0.012176,0.926211,0.000000e+00,0.005635,0.012176,0.022184,0.036262,0.049671,0.108182,0.926211

In [ ]:
columns = [pair for pair in df.columns if pair[-1] == "mean"]
df = df.loc[:, columns]

df.columns = [c[0] for c in df.columns]

df

,coverage,mae,rmse,mse,median_ae,max_ae,ae_q00,ae_q25,ae_q50,ae_q75,ae_q90,ae_q95,ae_q99,ae_q100
model,,,,,,,,,,,,,,
extra_trees,1.000000,0.003947,0.008826,0.000078,0.002472,0.621666,0.000000e+00,0.000881,0.002472,0.005000,0.007956,0.010718,0.025056,0.621666
random_forest,1.000000,0.004069,0.008656,0.000075,0.002524,0.512438,5.551115e-18,0.000883,0.002524,0.005195,0.008337,0.011313,0.026104,0.512438
hist_gradient_boosting,1.000000,0.013090,0.027548,0.000759,0.007920,0.855376,7.139322e-08,0.003576,0.007920,0.014877,0.025358,0.036800,0.100711,0.855376
location_median,1.000000,0.110851,0.160910,0.025892,0.080000,1.624000,0.000000e+00,0.040000,0.080000,0.144000,0.220000,0.298000,0.592000,1.624000
global_median,1.000000,0.140664,0.196408,0.038576,0.110000,1.530000,0.000000e+00,0.050000,0.110000,0.190000,0.272000,0.360000,0.720000,1.530000
service_location_then_global,0.999996,0.017799,0.029421,0.000866,0.012176,0.926211,0.000000e+00,0.005635,0.012176,0.022184,0.036262,0.049671,0.108182,0.926211

In [ ]:
mapper: dict[str, str] = {
    "extra_trees": "ExtraTrees",
    "random_forest": "RandomForest",
    "hist_gradient_boosting": "HistGradientBoost",
    "location_median": "LocationMedian",
    "global_median": "GlobalMedian",
    "service_location_then_global": "AI-ASSIST",
}

df.index = df.index.map(mapper)

In [ ]:
df = df.sort_values("mae")
df

,coverage,mae,rmse,mse,median_ae,max_ae,ae_q00,ae_q25,ae_q50,ae_q75,ae_q90,ae_q95,ae_q99,ae_q100
model,,,,,,,,,,,,,,
ExtraTrees,1.000000,0.003947,0.008826,0.000078,0.002472,0.621666,0.000000e+00,0.000881,0.002472,0.005000,0.007956,0.010718,0.025056,0.621666
RandomForest,1.000000,0.004069,0.008656,0.000075,0.002524,0.512438,5.551115e-18,0.000883,0.002524,0.005195,0.008337,0.011313,0.026104,0.512438
HistGradientBoost,1.000000,0.013090,0.027548,0.000759,0.007920,0.855376,7.139322e-08,0.003576,0.007920,0.014877,0.025358,0.036800,0.100711,0.855376
AI-ASSIST,0.999996,0.017799,0.029421,0.000866,0.012176,0.926211,0.000000e+00,0.005635,0.012176,0.022184,0.036262,0.049671,0.108182,0.926211
LocationMedian,1.000000,0.110851,0.160910,0.025892,0.080000,1.624000,0.000000e+00,0.040000,0.080000,0.144000,0.220000,0.298000,0.592000,1.624000
GlobalMedian,1.000000,0.140664,0.196408,0.038576,0.110000,1.530000,0.000000e+00,0.050000,0.110000,0.190000,0.272000,0.360000,0.720000,1.530000

In [ ]:
df.to_csv("./bus39-5fold-report.csv")